notifications:
  email:
    recipients:
      - raffaello.bonghi@officinerobotiche.it
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always

language: c

sudo: true

addons:
  apt:
    packages:
    - libc6:i386
    - libx11-6:i386
    - libxext6:i386
    - libstdc++6:i386
    - libexpat1:i386

before_install:
 - chmod +x travis-install-dependencies.sh
 - chmod +x travis-install-dependencies-unav.sh

# Install needed IDE and compiler
install:
 - ./travis-install-dependencies.sh
 - ./travis-install-dependencies-unav.sh

# Generate Makefiles and make
script:
 - pwd
 - /opt/microchip/mplabx/v3.50/mplab_ide/bin/prjMakefilesGenerator.sh .
 - make
