language: c

# whitelist
branches:
  only:
    - feature/travis-CI_integration

sudo: true

addons:
  apt:
    packages:
    - libc6:i386
    - libx11-6:i386
    - libxext6:i386
    - libstdc++6:i386
    - libexpat1:i386

before_install: 
 - chmod +x travis-install-dependencies.sh
 - chmod +x travis-install-dependencies-unav.sh

# Install needed IDE and compiler
install:
 - ./travis-install-dependencies.sh
 - ./travis-install-dependencies-unav.sh

# Generate Makefiles and make
script:
 - pwd
 - cd ../or_bus_c.X
 - pwd
 - /opt/microchip/mplabx/v3.15/mplab_ide/bin/prjMakefilesGenerator.sh .
 - make
 - cd ../or_kernel_c.X
 - pwd
 - /opt/microchip/mplabx/v3.15/mplab_ide/bin/prjMakefilesGenerator.sh .
 - make
 - cd ../or_common_c.X
 - pwd
 - /opt/microchip/mplabx/v3.15/mplab_ide/bin/prjMakefilesGenerator.sh .
 - make
 - cd ../uNAV.X
 - /opt/microchip/mplabx/v3.15/mplab_ide/bin/prjMakefilesGenerator.sh .
 - make
